### ISSUE TITLE
samples.zip link not working

### ISSUE THREAD

**Issue by BurguerJohn** [svip-lab/impersonator#1]
Link to samples.zip in OneDrive is showing as unavailable.

**Comment by StevenLiuWen** [comment]
@BurguerJohn We have updated the newest codes and correct the links which are not working. Please clone the most recent codes.

**Comment by BurguerJohn** [comment]
Alright! Thanks!

**Comment by bafonso** [comment]
Could we have terminal friendly links? Right now it requires a browser to download the files.

**Comment by piaozhx** [comment]
@bafonso 
Hi, I have updated the terminal version in [readme](https://github.com/svip-lab/impersonator/blob/master/README.md) , hope to help.
