### ISSUE TITLE
运行所有demo报Segmentation fault 

### ISSUE THREAD

**Issue by hitwangshuai** [svip-lab/impersonator#10]
hi，您好，运行你们的demo程序报segmentation fault

**Comment by piaozhx** [comment]
make sure you have installed neural_renderer successfully. if you are windows user, #2 may help.

**Comment by JasonBoy1** [comment]
> make sure you have installed neural_renderer successfully. if you are windows user, #2 may help.

Hi, could you work with Cuda 9.0?

**Comment by piaozhx** [comment]
@JasonBoy1 cuda 9.0 works well, it will be helpful if you could provide more detial about your problem (e.g. error message and develop environment)

**Comment by JasonBoy1** [comment]
> @JasonBoy1 cuda 9.0 works well, it will be helpful if you could provide more detial about your problem (e.g. error message and develop environment)

Dear piaozhx: thx for your quick reply. I have met such an error:

<ImportError: /mnt/lustre/wangwenjia/.local/lib/python3.6/site-packages/neural_renderer-1.1.3-py3.6-linux-x86_64.egg/neural_renderer/cuda/load_textures.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c1011CPUTensorIdEv

my torch version:
<torch.__version__    '1.3.1+cuda90_cudnn7.6.3_lms'

**Comment by piaozhx** [comment]
refer #35, usually it is caused by different cuda version of pytorch and  local cuda environment, 
try these solutions step by step:
(1) make sure you have same cuda version
(2) remove all files in `/mnt/lustre/xxx/.local/lib/python3.6/site-packages/neural_renderer-1.1.3-py3.6-linux-x86_64.egg/neural_renderer` and other compiled files in `thirdparty/neural_renderer` (recommend replacing it with a clean version),
(3) install neural_render again.

**Comment by JasonBoy1** [comment]
> refer #35, usually it is caused by different cuda version of pytorch and local cuda environment,
> try these solutions step by step:
> (1) make sure you have same cuda version
> (2) remove all files in `/mnt/lustre/xxx/.local/lib/python3.6/site-packages/neural_renderer-1.1.3-py3.6-linux-x86_64.egg/neural_renderer` and other compiled files in `thirdparty/neural_renderer` (recommend replacing it with a clean version),
> (3) install neural_render again.

I found that in /usr/local/cuda/version.txt, my cuda version is **8.0.61**. while in nvcc-v, it is **Cuda compilation tools, release 9.0, V9.0.176**. That's weird, how to fix this? 
Thanks a lot.

**Comment by piaozhx** [comment]
maybe you have installed multiple version of cuda and you just forget it, so a simple solution is 
removing old version and installing correct version of cuda (maybe use `which nvcc` could provide some clues)

**Comment by JasonBoy1** [comment]
> maybe you have installed multiple version of cuda and you just forget it, so a simple solution is
> removing old version and installing correct version of cuda (maybe use `which nvcc` could provide some clues)

Hi, I think I have installed the cuda and torch right.
- torch.__version__ '1.1.0'  
- nvcc -V release 9.0, V9.0.176
but still segmentation fault.
I re-installed neural-render, and only one warning:
` /mnt/cache/share/spring/conda_envs/miniconda3/envs/r0.3.0/lib/python3.6/site-packages/torch/utils/cpp_extensi$
n.py:191: UserWarning:

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (g++ 4.8.5) may be ABI-incompatible with PyTorch!
Please use a compiler that is ABI-compatible with GCC 4.9 and above.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.

See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
for instructions on how to install GCC 4.9 or higher.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))'

**Comment by JasonBoy1** [comment]
```
/mnt/cache/share/spring/conda_envs/miniconda3/envs/r0.3.0/lib/python3.6/site-packages/torch/utils/cpp_extensi$
n.py:191: UserWarning:

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (g++ 4.8.5) may be ABI-incompatible with PyTorch!
Please use a compiler that is ABI-compatible with GCC 4.9 and above.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.

See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
for instructions on how to install GCC 4.9 or higher.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
building 'neural_renderer.cuda.load_textures' extension
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/neural_renderer
creating build/temp.linux-x86_64-3.6/neural_renderer/cuda
gcc -pthread -B /mnt/cache/share/spring/conda_envs/miniconda3/envs/r0.3.0/compiler_compat -Wl,--sysroot=/ -Wsi
gn-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/mnt/cache/share/spring/conda_envs/minico
nda3/envs/r0.3.0/lib/python3.6/site-packages/torch/include -I/mnt/cache/share/spring/conda_envs/miniconda3/env
s/r0.3.0/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/mnt/cache/share/spring/conda_envs
/miniconda3/envs/r0.3.0/lib/python3.6/site-packages/torch/include/TH -I/mnt/cache/share/spring/conda_envs/mini
conda3/envs/r0.3.0/lib/python3.6/site-packages/torch/include/THC -I/mnt/cache/share/cuda-9.0/include -I/mnt/ca
che/share/spring/conda_envs/miniconda3/envs/r0.3.0/include/python3.6m -c neural_renderer/cuda/load_textures_cu
da.cpp -o build/temp.linux-x86_64-3.6/neural_renderer/cuda/load_textures_cuda.o -DTORCH_API_INCLUDE_EXTENSION_
H -DTORCH_EXTENSION_NAME=load_textures -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: 警告：command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [默认启用]
In file included from neural_renderer/cuda/load_textures_cuda.cpp:1:0:
/mnt/cache/share/spring/conda_envs/miniconda3/envs/r0.3.0/lib/python3.6/site-packages/torch/include/torch/csrc
/api/include/torch/torch.h:7:2: 警告：#warning "Including torch/torch.h for C++ extensions is deprecated. Plea
se include torch/extension.h" [-Wcpp]
 #warning \
  ^
/mnt/cache/share/cuda-9.0/bin/nvcc -I/mnt/cache/share/spring/conda_envs/miniconda3/envs/r0.3.0/lib/python3.6/s
ite-packages/torch/include -I/mnt/cache/share/spring/conda_envs/miniconda3/envs/r0.3.0/lib/python3.6/site-pack
ages/torch/include/torch/csrc/api/include -I/mnt/cache/share/spring/conda_envs/miniconda3/envs/r0.3.0/lib/pyth
on3.6/site-packages/torch/include/TH -I/mnt/cache/share/spring/conda_envs/miniconda3/envs/r0.3.0/lib/python3.6
/site-packages/torch/include/THC -I/mnt/cache/share/cuda-9.0/include -I/mnt/cache/share/spring/conda_envs/mini
conda3/envs/r0.3.0/include/python3.6m -c neural_renderer/cuda/load_textures_cuda_kernel.cu -o build/temp.linux
-x86_64-3.6/neural_renderer/cuda/load_textures_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CON
VERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EX
TENSION_NAME=load_textures -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
/mnt/cache/share/spring/conda_envs/miniconda3/envs/r0.3.0/lib/python3.6/site-packages/torch/include/c10/util/A
rrayRef.h:277:48: 警告：‘deprecated’属性指定被忽略 [-Wattributes]
 using IntList C10_DEPRECATED_USING = ArrayRef<int64_t>;
                                                ^
neural_renderer/cuda/load_textures_cuda_kernel.cu: 在 lambda 函数中:
neural_renderer/cuda/load_textures_cuda_kernel.cu:80:120: 警告：不建议使用‘c10::ScalarType detail::scalar_type
(const at::DeprecatedTypeProperties&)’(声明于 /mnt/cache/share/spring/conda_envs/miniconda3/envs/r0.3.0/lib/py
thon3.6/site-packages/torch/include/ATen/Dispatch.h:47) [-Wdeprecated-declarations]
     AT_DISPATCH_FLOATING_TYPES(image.type(), "load_textures_cuda", ([&] {

          ^
```
so many warnings, still could not install...

**Comment by piaozhx** [comment]
I notice that your gcc version is 4.8.5, which could be a problem (I guess your os is ubuntu14.04 or centos 6.x, which is old for pytorch), upgrading gcc to 4.9 or 5.4 maybe a good choice.

**Comment by JasonBoy1** [comment]
> I notice that your gcc version is 4.8.5, which could be a problem (I guess your os is ubuntu14.04 or centos 6.x, which is old for pytorch), upgrading gcc to 4.9 or 5.4 maybe a good choice.

Thanks, I shall try. I can import every function and class in neural_render. Only fail at 
```
nr.rasterize_face_index_map_and_weight_map(faces, self.image_size, False)
```
I guess the problem lies in GCC version.
Thanks again for your selflessness!

**Comment by JasonBoy1** [comment]
> I notice that your gcc version is 4.8.5, which could be a problem (I guess your os is ubuntu14.04 or centos 6.x, which is old for pytorch), upgrading gcc to 4.9 or 5.4 maybe a good choice.

It works. I used GCC 5.4.0. Thx again.
