### ISSUE TITLE
ImportError: load_textures.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E

### ISSUE THREAD

**Issue by BolinLi-s** [svip-lab/impersonator#13]
when i run demo_imitator.py I got↓

Traceback (most recent call last):
  File "demo_imitator.py", line 6, in <module>
    from models.imitator import Imitator
  File "/home/lbl/impersonator/models/imitator.py", line 8, in <module>
    from utils.nmr import SMPLRenderer
  File "/home/lbl/impersonator/utils/nmr.py", line 11, in <module>
    import neural_renderer as nr
  File "/home/lbl/anaconda3/lib/python3.7/site-packages/neural_renderer/__init__.py", line 3, in <module>
    from .load_obj import load_obj
  File "/home/lbl/anaconda3/lib/python3.7/site-packages/neural_renderer/load_obj.py", line 8, in <module>
    import neural_renderer.cuda.load_textures as load_textures_cuda
ImportError: /home/lbl/anaconda3/lib/python3.7/site-packages/neural_renderer/cuda/load_textures.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E

**Comment by piaozhx** [comment]
It seems that the nerual renderer you installed don't match to your python version.
 e.g. you installed it with python3.6 but run demo_imitator.py with python3.7. maybe you should 
create a new python environment and install nerual renderer again

**Comment by studabyd** [comment]
> when i run demo_imitator.py I got↓
> 
> Traceback (most recent call last):
> File "demo_imitator.py", line 6, in
> from models.imitator import Imitator
> File "/home/lbl/impersonator/models/imitator.py", line 8, in
> from utils.nmr import SMPLRenderer
> File "/home/lbl/impersonator/utils/nmr.py", line 11, in
> import neural_renderer as nr
> File "/home/lbl/anaconda3/lib/python3.7/site-packages/neural_renderer/**init**.py", line 3, in
> from .load_obj import load_obj
> File "/home/lbl/anaconda3/lib/python3.7/site-packages/neural_renderer/load_obj.py", line 8, in
> import neural_renderer.cuda.load_textures as load_textures_cuda
> ImportError: /home/lbl/anaconda3/lib/python3.7/site-packages/neural_renderer/cuda/load_textures.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E

Have you solved this error, maybe I meet this, how did you solve it, thank you
