### ISSUE TITLE
No results

### ISSUE THREAD

**Issue by MarioProjects** [svip-lab/impersonator#18]
After run some examples, I cannot find the ouput in the output_dir. Running runDetails.md examples

**Comment by StevenLiuWen** [comment]
@MarioProjects , Hi, The runDeailts.md illustrates the meanings of some important flags. 
To be simplified, we take the following examples 
```bash
python run_imitator.py --gpu_ids 0 --model imitator --output_dir ./outputs/results/  \
    --src_path      ./assets/src_imgs/imper_A_Pose/009_5_1_000.jpg    \
    --tgt_path      ./assets/samples/refs/iPER/024_8_2    \
    --bg_ks 13  --ft_ks 3 \
    --has_detector  --post_tune  \
--save_res  --output_dir  /data/test_results
```

Here, we point the `output_dir` to `/data/test_results`, and thereby results are saved in `/data/test_results/imitators`, and the synthesized images are named as `pred_xxxx.jpg`. We only save them as images, and in the next version, we will make the final results as a video (using the tools, such as `ffmepg`).
