### ISSUE TITLE
Can you run this on a 8gb nvidia 1070?

### ISSUE THREAD

**Issue by bafonso** [svip-lab/impersonator#19]
Has anyone successfully used a 1070 with 8GB? I can't run the demo code while using the 1070 for display but I wonder if I dedicate it for CUDA it will work.

`RuntimeError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 7.93 GiB total capacity; 5.94 GiB already allocated; 41.25 MiB free; 252.07 MiB cached)`

**Comment by StevenLiuWen** [comment]
@bafonso  , Hi, we have optimized the minimal requirements of GPU memory and updated the codes righit now. 
If you get the errors, `RuntimeError: CUDA out of memory`, please add the flag `--batch_size 1`. 
For example, 
```bash
python demo_imitator.py --gpu_ids 1 --batch_size 1
```
The usage of GPU memory is 3.8 GB (tested on my GTX 1080).
