### ISSUE TITLE
Sorry to bother you. Can this project run on cuda9.0? thx!

### ISSUE THREAD

**Issue by OldChi** [svip-lab/impersonator#35]

**Comment by OldChi** [comment]
i run "python demo_imitator.py --gpu_ids 1" on cuda9.0, torch1.1, torchvision0.3 and encountered an error:

 import neural_renderer.cuda.load_textures as load_textures_cuda
ImportError: /home/huangxinkai/env/impersonator/lib/python3.6/site-packages/neural_renderer-1.1.3-py3.6-linux-x86_64.egg/neural_renderer/cuda/load_textures.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_29E

could you please give me a hand and solve this?thx!

**Comment by taotaoyuhust** [comment]
i run it on cuda9.2 ,windows 10, torch1.2, torchvision 0.4.1

**Comment by piaozhx** [comment]
@OldChi I think cuda9.0 is ok for this project. You should make sure your pytorch cuda version(usually is selected on the pytorch website when you download pytorch) and local cuda version(could be found in /usr/local/cuda/version.txt) are same.

**Comment by OldChi** [comment]
> @OldChi I think cuda9.0 is ok for this project. You should make sure your pytorch cuda version(usually is selected on the pytorch website when you download pytorch) and local cuda version(could be found in /usr/local/cuda/version.txt) are same.

thank you! my cuda version is 9.0.
i downloaded the whl file of torchvision0.3 and torch1.1(cuda 9.0 build) on the pytorch website and installed it, but the same error appeared

**Comment by piaozhx** [comment]
remove all files in `/home/huangxinkai/env/impersonator/lib/python3.6/site-packages/neural_renderer-1.1.3-py3.6-linux-x86_64.egg` and other compiled files in `thirdparty/neural_renderer` (recommend replacing it with a clean version), then install `neural_render` again.

**Comment by OldChi** [comment]
> remove all files in `/home/huangxinkai/env/impersonator/lib/python3.6/site-packages/neural_renderer-1.1.3-py3.6-linux-x86_64.egg` and other compiled files in `thirdparty/neural_renderer` (recommend replacing it with a clean version), then install `neural_render` again.

thanks! now i can run demo_imitator.py successfully. you guys have really done a cool job! bravo!

here's another question:

i've try run_imitator.py and i notice that the face in the outputs looks like the face from tgt_path, how do i solve this problem so that i can make a new output with a new face from the source?

ps: i only modify the --src_path attribute to put in a new picture. is there something wrong?

python run_imitator.py --gpu_ids 0 --model imitator --output_dir ./outputs/results/  \
    --src_path      ./assets/src_imgs/imper_A_Pose/009_5_1_000.jpg    \
    --tgt_path      ./assets/samples/refs/iPER/024_8_2    \
    --bg_ks 13  --ft_ks 3 \
    --has_detector  --post_tune  \
    --save_res --ip my_IP

what's more, those mp4 files in samples\refs\mixamo must be useful. how can i create a new video based on these mp4s and a picture of a new person?

thanks a lot!

**Comment by OldChi** [comment]
> remove all files in `/home/huangxinkai/env/impersonator/lib/python3.6/site-packages/neural_renderer-1.1.3-py3.6-linux-x86_64.egg` and other compiled files in `thirdparty/neural_renderer` (recommend replacing it with a clean version), then install `neural_render` again.

thank you very much! now i'm running the _imitator_ successfully. you guys have really done a cool job. bravo!!

here's a little question:
i want to run some customs examples using _imitator_. and i wonder if there are some constraints on my _reference_ pictures, for example, the image size? the character's position in the image? the character's background? how could i modify the _reference_ pictures or the codes so that i could get good results as you guys did?

thanks again

**Comment by OldChi** [comment]
> remove all files in `/home/huangxinkai/env/impersonator/lib/python3.6/site-packages/neural_renderer-1.1.3-py3.6-linux-x86_64.egg` and other compiled files in `thirdparty/neural_renderer` (recommend replacing it with a clean version), then install `neural_render` again.

excuse me. i've converted my own video file into 544*544*3 images and i used run_imitator.py to swap the man inside my video. but an error occured. what should i do to run it successfully. 

Traceback (most recent call last):
  File "run_imitator.py", line 225, in <module>
    adaptive_personalize(test_opt, imitator, visualizer)
  File "run_imitator.py", line 203, in adaptive_personalize
    imitator.personalize(opt.src_path, visualizer=None)
  File "/home/huangxinkai/env/impersonator/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 43, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/huangxinkai/project/impersonator/models/imitator.py", line 125, in personalize
    src_info['bg'] = self.bgnet(img, masks=body_mask, only_x=True)
  File "/home/huangxinkai/env/impersonator/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/huangxinkai/project/impersonator/networks/inpaintor.py", line 180, in forward
    masked_imgs = imgs * (1 - masks) + masks
RuntimeError: The size of tensor a (256) must match the size of tensor b (257) at non-singleton dimension 3

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Comment by AKclown** [comment]
> thirdparty/neural_renderer

I did not find the thirdparty/neural_renderer directory, pip uninstall neural_renderer_pytorch and then re-execute pip install neural_renderer_pytorch, sh scripts/run_car.sh and still report errors. What should I do?
