### ISSUE TITLE
Training dataset with corrupted ZIP archive ("smpls.zip")

### ISSUE THREAD

**Issue by AndroXD** [svip-lab/impersonator#36]
Hello, the provided training data at your [OneDrive](https://onedrive.live.com/?authkey=%21AJL_NAQMkdXGPlA&id=3705E349C336415F%2188052&cid=3705E349C336415F) link have a file named "smpls.zip" that appears to be corrupted, it doesn't unzip correctly in both Windows and Linux, even using tools such as 7-Zip and WinRar, it reports a bad zipfile offset at several points (from file #146 to #735), I re-downloaded it 4 times already and kept an eye on the progress bar to make sure there were no interruptions.
Could you please check if the provided file is okay? Thanks!

**Comment by zrhyst23** [comment]
> Hello, the provided training data at your [OneDrive](https://onedrive.live.com/?authkey=%21AJL_NAQMkdXGPlA&id=3705E349C336415F%2188052&cid=3705E349C336415F) link have a file named "smpls.zip" that appears to be corrupted, it doesn't unzip correctly in both Windows and Linux, even using tools such as 7-Zip and WinRar, it reports a bad zipfile offset at several points (from file #146 to #735), I re-downloaded it 4 times already and kept an eye on the progress bar to make sure there were no interruptions.
> Could you please check if the provided file is okay? Thanks!
  I have the same problem , have you got sovled?

**Comment by AndroXD** [comment]
I repaired the archive using Winrar [repair option](https://i.imgur.com/IZTgsut.png) and I could extract all files, I'm not sure if there's anything corrupted, but so far the training has been running smoothly without any noticeable error.

**Comment by piaozhx** [comment]
@AndroXD @zrhyst23  we have uploaded a new lighter version of `smpls.zip` (remove some useless midterm variable) and now it's about 100MB, you can download the new one in same link.

**Comment by zhyj3038** [comment]
Hi, can you please upload the train dataset to BaiduPan? 
the oneDive seems difficult to open .
Thanks Very much!!!
