### ISSUE TITLE
Is a higher resolution iPER dataset currently available?

### ISSUE THREAD

**Issue by AndroXD** [svip-lab/impersonator#38]
Hello, would it be possible to download a higher resolution iPER dataset somewhere or somehow? I'm really interested in it, thanks!

**Comment by StevenLiuWen** [comment]
@AndroXD , 
Hi, we upload the 1024 x 1024 resolution videos of iPER dataset on https://onedrive.live.com/?authkey=%21AJL_NAQMkdXGPlA&id=3705E349C336415F%2188052&cid=3705E349C336415F, named `iPER_1024_video_release.zip`.

**Comment by OldChi** [comment]
> @AndroXD ,
> Hi, we upload the 1024 x 1024 resolution videos of iPER dataset on https://onedrive.live.com/?authkey=%21AJL_NAQMkdXGPlA&id=3705E349C336415F%2188052&cid=3705E349C336415F, named `iPER_1024_video_release.zip`.

can I download a high resolution video by myself for motion imitation module?

**Comment by StevenLiuWen** [comment]
@OldChi , Currently, if you want to generate higher resolution results such as 512 x 512, you need to train the model at this resolution.

**Comment by OldChi** [comment]
> @OldChi , Currently, if you want to generate higher resolution results such as 512 x 512, you need to train the model at this resolution.

hi I trained on your 1024*1024 data and set image size to 512 during training. however, using the result, I still generated 256*256 images, how can i modify the code so that i can generate 512*512 images?
