### ISSUE TITLE
TypeError on Windows demo_imitator.py

### ISSUE THREAD

**Issue by gdlf** [svip-lab/impersonator#39]
Hi,

I have tackled all the issues before running the actual demo on Windows and I got this error:

  File "base_options.py", line 67, in set_zero_thread_for_Win
    if 'n_threads_test' in self._opt.__class__:
TypeError: argument of type 'type' is not iterable

Anyone resolved this?

**Comment by StevenLiuWen** [comment]
@gdlf It's a bug in the last version, and please clone the latest codes.
