### ISSUE TITLE
About details: why you use 1 discriminator(4 layers) and use three label(-1,0,1) ?

### ISSUE THREAD

**Issue by dypromise** [svip-lab/impersonator#47]
Hi, author!
I have read your paper and your code, and i have some questions which confused me. recently pix2pixHD is famous, why you just use  one-scale discriminator and using three labels(-1, 0, 1) instead of using 2-scale Discriminator? and using three label( -1, 0, 1) have advantages than two labels style(e.g. in pix2pixHD, they use 0,1 for fake and real)? thanks for your reply!

**Comment by dypromise** [comment]
another difference, your work use 4 layers in D,  while in pix2pixHD, they use 3 layers but two-scale. Do you have any reason about your design?

**Comment by StevenLiuWen** [comment]
Hi, @dypromise 
We follow the LSGAN-V2 (the journal version https://arxiv.org/pdf/1712.06391.pdf, see 3.4 Parameters Selection in this paper). In this version, they found that the label (-1, 0, 1) is better than the vanilla LSGAN where the label is (0, 0, 1).
