### ISSUE TITLE
IndexError: tensors used as indices must be long, byte or bool tensors

### ISSUE THREAD

**Issue by JinglUO703** [svip-lab/impersonator#5]
![G`476VFFL)UXJP `R{9LRDK](https://user-images.githubusercontent.com/49707474/65831096-58b41e00-e2e8-11e9-8652-56b9bff8b0f6.png)

**Comment by fuzuoyi** [comment]
`    res[indices.cpu().numpy()] = updates
`
that will work

**Comment by StevenLiuWen** [comment]
@JinglUO703 It be fixed by the followings:

`    # indices = torch.from_numpy(np.reshape(
    #     np.reshape(np.arange(0, batch_size) * 9, [-1, 1]) + col_inds,
    #     newshape=(-1,))).to(device)

    # For better compatibility， since if indices is torch.tensor, it must be long dtype.
    # For fixed index, np.ndarray might be better.
    indices = np.reshape(np.reshape(np.arange(0, batch_size) * 9, [-1, 1]) + col_inds, newshape=(-1, ))`

**Comment by StevenLiuWen** [comment]
@JinglUO703 It can be fixed by following codes:
```Python
    # indices = torch.from_numpy(np.reshape(
    #     np.reshape(np.arange(0, batch_size) * 9, [-1, 1]) + col_inds,
    #     newshape=(-1,))).to(device)

    # For better compatibility， since if indices is torch.tensor, it must be long dtype.
    # For fixed index, np.ndarray might be better.
    indices = np.reshape(np.reshape(np.arange(0, batch_size) * 9, [-1, 1]) + col_inds, newshape=(-1, ))
```

**Comment by JinglUO703** [comment]
> ` res[indices.cpu().numpy()] = updates`
> 那可行

**Comment by JinglUO703** [comment]
> ` res[indices.cpu().numpy()] = updates`
> 那可行

Thanks,at first I thought it was numpy version

**Comment by JinglUO703** [comment]
> @ JinglUO703
> 
> 1. 快速的方法是
> 
> ```python
> res [indices.long（）] =更新
> ```
> 
> 1. （可选方式）而且，由于`indices`这里不是动态索引，因此np.ndarray的兼容性可能更好。可以通过以下代码进行修复：
> 
> ```python
> ＃索引= torch.from_numpy（np.reshape（
> ＃      np.reshape（np.arange（0，batch_size）* 9，[-1，1]）+ col_inds，
> ＃      newshape =（-1，）））。to（设备）
> 
> ＃为了更好的兼容性，由于索引为torch.tensor，因此必须为long dtype。
> ＃对于固定索引，np.ndarray可能更好。
> 指数 = np.reshape（np.reshape（np.arange（ 0，的batch_size） *  9，[ - 1， 1 ]） + col_inds， newshape =（ - 1））
> ```
> 
> 我们将尽快修复此问题，@ fuzuoyi提出的解决方案也是可行的。

3Q,I have solved this problem through @fuzuoyi  method.
