### ISSUE TITLE
Eval protocol?

### ISSUE THREAD

**Issue by isarandi** [svip-lab/impersonator#54]
Dear Authors, thank you for uploading the code for your paper, it's very useful. However, one missing piece is the evaluation: I could not find an evaluation script in the repository. Can you describe the evaluation protocol, i.e. exactly which set of (source image, target pose) pairs are used to compute the metrics, or if it's based on random sampling how that sampling is performed? Thank you!

**Comment by StevenLiuWen** [comment]
Hi, @isarandi, we have release the recent evaluation protocols. Please clone the recent codes, and see https://github.com/svip-lab/impersonator/tree/master/thirdparty/his_evaluators for more details.

**Comment by StevenLiuWen** [comment]
Hi, @isarandi , you can find the evaluation code, there https://github.com/svip-lab/impersonator/tree/master/thirdparty/his_evaluators,
