### ISSUE TITLE
Bad results with my own data

### ISSUE THREAD

**Issue by syp1997** [svip-lab/impersonator#56]
I used my own source image and dance videos, but get bad results, how can i solve it?

**Comment by StevenLiuWen** [comment]
@syp1997 , Hi, since the model has been pre-trained on the iPER dataset, and the iPER dataset has the shortcomings in the diversity, especially in the background, you might need to firstly train the model on you own dataset, and see https://github.com/svip-lab/impersonator/issues/28 more details.
