### ISSUE TITLE
ImportError: /home/robot/wjs/impersonator/thirdparty/neural_renderer/neural_renderer_new/cuda/load_textures.cpython-36m-x86_64-linux-gnu.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Wu-JiaSheng** [svip-lab/impersonator#59]
Sorry to bother you,but i cant solve this problem in title when i run python demo_imitator.py  thank you very much

**Comment by StevenLiuWen** [comment]
Hi, @Wu-JiaSheng , you can refer to https://github.com/svip-lab/impersonator/issues/35 for more details
