### ISSUE TITLE
AttributeError: module 'neural_renderer' has no attribute 'rasterize_face_index_map_and_weight_map'

### ISSUE THREAD

**Issue by fanchunpeng** [svip-lab/impersonator#60]
AttributeError: module 'neural_renderer' has no attribute 'rasterize_face_index_map_and_weight_map'？？？

**Comment by StevenLiuWen** [comment]
Hi, @fanchunpeng , we have modified some implementation of the original version of neural_renderer. You might need to install ours' implementation, https://github.com/svip-lab/impersonator/tree/master/thirdparty/neural_renderer.
