### ISSUE TITLE
 error: neural_renderer/cuda/load_textures_cuda.cpp

### ISSUE THREAD

**Issue by Hitesh-Nagothu** [svip-lab/impersonator#62]
Using Ubuntu Environment| Cuda 10.0 | Tried Pytorch 1.2.0 and 1.3.0
Getting the below error:

 **error: neural_renderer/cuda/load_textures_cuda.cpp**

Any help will be appreciated. Thank you.

**Comment by Hitesh-Nagothu** [comment]
Update: error: /util/common/cuda/cuda-9.2/bin/nvcc' failed with exit status 1

**Comment by StevenLiuWen** [comment]
Hi @Hitesh-Nagothu , is it the error when installing the neural_renderer (https://github.com/svip-lab/impersonator#installation)? If it is, you might need to provide a snapshot of the error messages for us. Maybe we can help you to install it.

**Comment by Hitesh-Nagothu** [comment]
Fixed the issue. Thanks for response @StevenLiuWen
